### ISSUE TITLE
Publish Roblox OAuth 2.0 Apps

### ISSUE THREAD

**Issue by torodavit** [treeben77/rblx-open-cloud#18]
Hello, I register OAuth 2.0 Apps, I have iOS app and implemented this OAuth app in it. it's work perfect. I need publish it, but rejected. entry link is not correct, they sad. I don't have web page. I only have mobile app. What can I do about entry link?

**Comment by treeben77** [comment]
Roblox is very strict with entry links and it is a big pain to deal with. I haven't personally delt with mobile apps (and impressed you've used my library with an iOS app) but a strategy I have done is set the entry link to a GitHub gist with step-by-step instruction on using your app, an example that I used with a Discord bot can be seen here: https://gist.github.com/treeben77/a60cd0e8fcd682e4fd3f8ce7b7fb241b

I'm not sure if Roblox would still accept a gist like that since it's been quite a while since I used that method, so if it doesn't work let me know and we can go from there.
