### ISSUE TITLE
Operation erroring with a ratelimit but asset is uploaded

### ISSUE THREAD

**Issue by wclxb** [treeben77/rblx-open-cloud#20]
When using a Creator to upload an asset, it keeps erroring with a ratelimit even though the asset is actually getting uploaded.

**Comment by treeben77** [comment]
Hello, thanks for your issue! I am unable to replicate your issue; are you able to provide a snippet of the code you are using?

**Comment by treeben77** [comment]
This issue has been resolved in the Discord server. If anyone else has the same issue it is likely due to Roblox changing their rate limits. As such, the solution is to include the following parameters in the [`wait`](https://rblx-open-cloud.readthedocs.io/en/latest/reference/library.html#rblxopencloud.Operation.wait) call:
```py
.wait(
    interval_seconds=3,
    timeout_seconds=180 # don't set to None because program may hang forever.
)
```
Note that this solution will utilise [exponential back-off](https://en.wikipedia.org/wiki/Exponential_backoff), as recommended by Roblox staff because `interval_exponent` is equal to `1.3` by default. Set this to 1 to disable this behaviour.
